export default (config = {
  POST_RETURN_LIMIT: 9,
  PROFILE_POST_RETURN_LIMIT: 10,
  COMMENT_RETURN_LIMIT: 10,
  REPLY_RETURN_LIMIT: 10,
  SEARCH_RETURN_LIMIT: 10,
  USER_RETURN_LIMIT: 10,
  MESSAGE_RETURN_LIMIT: 10,
  RECOMMENDED_POST_RETURN_LIMIT: 24,
  TAG_SELECT_LIMIT: 10,
  MENTIONED_USER_SELECT_LIMIT: 20,
  HOT_TAG_TOPIC_RETURN_LIMIT: 10,
  AJAX_QUERY_DURATION: 1000, // millisecond
  MAX_DISTANCE: 5000,
  MAX_COUNT_UPLOAD: 9
});
