export const CLIENT_INFO = "CLIENT_INFO";
export const LOGIN_CREDENTIALS = "LOGIN_CREDENTIALS";
export const APP_LOCALE = "APP_LOCALE";
export const PERMISSION_CAMERA = "PERMISSION_CAMERA";
export const PERMISSION_LIBRARY = "PERMISSION_LIBRARY";
export const PERMISSION_LOCATION = "PERMISSION_LOCATION";
